### ISSUE TITLE
Renew SSL Certificate

### ISSUE THREAD

**Issue by danielcompton** [clojars/infrastructure#20]
It expires on 12 August, needs to be renewed before then, and should use SHA-2.

**Comment by tobias** [comment]
Thanks for the reminder - we also have a test that will start failing 60 days out: https://github.com/clojars/clojars-web/tree/master/test/clojars/test/unit/certs.clj#L12

We should check to make sure SHA-2 (and whatever other cert options we choose) works with java 6, since we still have some users on it.

**Comment by tobias** [comment]
And I just saw #19 :)
