### ISSUE TITLE
Configure gzip in nginx

### ISSUE THREAD

**Issue by danielcompton** [clojars/infrastructure#22]
clojars.org doesn't seem to be gzipping assets. It would be good to figure out why, as it seems like it should be based on the [config](https://github.com/clojars/clojars-server-config/blob/master/roles/clojars/templates/nginx.conf.j2#L19-L20).

**Comment by spencercrissman** [comment]
Can you comment on specifics? The compression generally seems to be working.

I did note a couple things:
- When you visit clojars, you might notice that many of the responses do not have the Content-Encoding gzip header. At first this led me to believe the compression was not working, but after reviewing, in the cases where I was not seeing it, it was because the 'request' was actually getting a 304 response and the item was being served from local cache. A force refresh of the asset resulted in a 200 response and the content encoding indicating it was gzipped:

<img width="405" alt="css-gzipped" src="https://cloud.githubusercontent.com/assets/524593/19177203/de069016-8c14-11e6-8ccb-56ff637f08c7.png">
- The zipping is only working for the file types specified. Generally speaking I think most things are being covered that should be. The only exception I found was xml files, which are being served up as mime type text/xml rather than application/xml, resulting in those being missed. I've issued a pull request to resolve that. pom files are being served as text/plain, so they were fine.

**Comment by danielcompton** [comment]
I don't remember specifics, you're probably right about the 304's though.
